theme_color: '#04B575' # dark green
# theme_color: '#ff7373' # salmon
# theme_color: '#468499' # blue
# theme_color: '#8a2be2' # violet

print_surah:
  show_arabic: false

print_ayat:
  show_arabic: false
